### ISSUE TITLE
nonce

### ISSUE THREAD

**Issue by crypt0inf0** [iWarpBTC/mining#1]
Why the nonce on [000000000000000000028488503aa80f9e469b1ee119335f99c766f172c061ea](https://mempool.space/block/000000000000000000028488503aa80f9e469b1ee119335f99c766f172c061ea?showDetails=true&view=actual#details) is `0x1437a129` different from the `0x29a13714`?

**Comment by iWarpBTC** [comment]
Hey! This is just the same, only in a different endianness. It's just a different byte order. I can see I've messed it up (cause little-endian goes into a header serializion) in my demo and it's really confusing. Gonna fix! Thanks for the catch.
